# Site
name: "Mojo"
description: "A blog for coffee shop owners and managers made by Mojo."
meta_description: "A blog for coffee shop owners and managers made by Mojo."
logo: 'assets/images/mojo_logo.png'
favicon: 'assets/images/mojo_favicon.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  drew:
    name: drew
    display_name: Drew Bidlen
    avatar: 'assets/images/drew_profile_pic.png'
    email: drew@mojocoffee.io
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  noah:
    name: noah
    display_name: Noah Bragg
    avatar: 'assets/images/noah_profile_pic.png'
    email: noah@mojocoffee.io
    web: https://twitter.com/NoahBraggg
    twitter: https://twitter.com/NoahBraggg
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge