# Site
name: "Mojo"
description: "A blog for coffee shop owners and managers made by Mojo."
meta_description: "A blog for coffee shop owners and managers made by Mojo."
logo: 'assets/images/mojo_logo.png'
favicon: 'assets/images/mojo_favicon.png'
baseurl: ''
google_analytics: 'UA-131045016-1'
disqus: ''
mailchimp-list: 'https://mojocoffee.us7.list-manage.com/subscribe/post?u=f030fcceb8790f91e569ead18&amp;id=4a1293845b'

# Authors
authors:
  drew:
    name: drew
    display_name: Drew Bidlen
    avatar: 'assets/images/drew_profile_pic.png'
    email: drew@mojocoffee.io
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  noah:
    name: noah
    display_name: Noah Bragg
    avatar: 'assets/images/noah_profile_pic.png'
    email: noah@mojocoffee.io
    web: https://twitter.com/NoahBraggg
    twitter: https://twitter.com/NoahBraggg
    description: "Co-founder of Mojo; a platform for independent coffee shops to offer order-ahead for their customers. Noah loves building software and creating an experience that really delights users! In his free time Noah enjoys reading, listening to podcasts, and playing with his little baby girl!"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge